"""Add competition table

Revision ID: 4ec2a44367f8
Revises: e5f9dac72943
Create Date: 2025-07-22 22:57:56.154546

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4ec2a44367f8"
down_revision = "e5f9dac72943"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "competition",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description_fr", sa.String(length=300), nullable=False),
        sa.Column("description_en", sa.String(length=300), nullable=False),
        sa.Column("lock_datetime", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("official_results_url", sa.String(length=300), nullable=False),
        sa.Column("rules", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("description_en"),
        sa.UniqueConstraint("description_fr"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("competition")
    # ### end Alembic commands ###
