"""Change bet locking mechanism

Revision ID: b877d7d6ef66
Revises: 9f8e020eeced
Create Date: 2023-03-06 23:50:41.623221

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "b877d7d6ef66"
down_revision = "9f8e020eeced"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("binary_bet", schema=None) as batch_op:
        batch_op.drop_column("locked")

    with op.batch_alter_table("score_bet", schema=None) as batch_op:
        batch_op.drop_column("locked")

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("locked", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("locked")

    with op.batch_alter_table("score_bet", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("locked", mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
        )

    with op.batch_alter_table("binary_bet", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("locked", mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
        )

    # ### end Alembic commands ###
