name: 🔂 Unit tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    paths:
      - "yak_server/**"
      - "tests/**"
      - "pyproject.toml"
      - "poetry.lock"
      - ".github/workflows/test.yml"

jobs:
  unit-tests:
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    name: Python test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: mysql --version
